package wallets

import (
	"strings"
	"testing"
)

func TestGenerateMnemonic(t *testing.T) {
	mnemonic, err := GenerateMnemonic()
	if err != nil {
		t.Fatalf("GenerateMnemonic() error = %v", err)
	}

	if mnemonic == "" {
		t.Errorf("GenerateMnemonic() returned an empty mnemonic string")
	}

	// Check if it's a 12-word mnemonic (default entropy)
	words := strings.Fields(mnemonic)
	if len(words) != 12 {
		t.Errorf("GenerateMnemonic() did not return a 12-word mnemonic, got %d words: %s", len(words), mnemonic)
	}

	// Further validation (optional, as library should handle this)
	if !ValidateMnemonic(mnemonic) {
		t.Errorf("GenerateMnemonic() returned a mnemonic that failed validation: %s", mnemonic)
	}
	t.Logf("Generated mnemonic: %s", mnemonic) // Log for manual inspection if needed
}

func TestValidateMnemonic(t *testing.T) {
	tests := []struct {
		name     string
		mnemonic string
		want     bool
	}{
		{
			name:     "Valid 12-word mnemonic",
			mnemonic: "legal winner thank year wave sausage worth useful legal winner thank yellow", // A known valid mnemonic
			want:     true,
		},
		{
			name:     "Valid 24-word mnemonic",
			mnemonic: "click plunge weasel zero load imitate inherit gas easily program spray artwork silver casino whale sponsor sail east jeans coast once ensure cement habit", // Generated by the library
			want:     true,
		},
		{
			name:     "Invalid mnemonic - too short",
			mnemonic: "legal winner thank year",
			want:     false,
		},
		{
			name:     "Invalid mnemonic - incorrect words",
			mnemonic: "notaword winner thank year wave sausage worth useful legal winner thank yellow",
			want:     false,
		},
		{
			name:     "Invalid mnemonic - empty string",
			mnemonic: "",
			want:     false,
		},
		{
			name:     "Invalid mnemonic - extra spaces",
			mnemonic: "  legal   winner  thank   year   wave   sausage   worth   useful  legal   winner  thank  yellow  ",
			want:     true, // The library handles trimming spaces
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := ValidateMnemonic(tt.mnemonic); got != tt.want {
				t.Errorf("ValidateMnemonic() = %v, want %v for mnemonic: %q", got, tt.want, tt.mnemonic)
			}
		})
	}
}
